# Generated by Django 5.1.1 on 2024-11-08 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_alter_enrollment_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Assessment Type',
                'verbose_name_plural': 'Assessment Types',
            },
        ),
        migrations.CreateModel(
            name='InvitedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invitation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('score_quiz', models.IntegerField(default=0, verbose_name='Quiz Score')),
                ('score_ass', models.IntegerField(default=0, verbose_name='Assignment Score')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_proctored', models.BooleanField(default=False)),
                ('proctoring_data', models.JSONField(default=dict, null=True)),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Assignment Attempt',
                'verbose_name_plural': 'Student Assignment Attempts',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('invited_count', models.IntegerField(default=0, verbose_name='Invited Count')),
                ('assessed_count', models.IntegerField(default=0, verbose_name='Assessed Count')),
                ('qualified_count', models.IntegerField(default=0, verbose_name='Qualified Count')),
                ('qualify_score', models.IntegerField(default=60, verbose_name='Qualify Score')),
                ('total_score', models.IntegerField(default=100, verbose_name='Total Score')),
                ('quiz_score_ratio', models.IntegerField(default=40, verbose_name='Quiz score ratio')),
                ('exercise_score_ratio', models.IntegerField(default=60, verbose_name='Exercise score ratio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_limit', models.IntegerField(default=30)),
                ('invited_emails', models.TextField(blank=True, verbose_name='Invited Candidates')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['created_at', 'course'],
            },
        ),
    ]
