# Generated by Django 5.1.1 on 2024-11-08 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('exercises', '0001_initial'),
        ('quiz', '0003_remove_studentanswer_selected_option_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='assessment', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assessment', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='assessments.assessmenttype'),
        ),
        migrations.AddField(
            model_name='invitedcandidate',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_candidates_list', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='assessments.studentassessmentattempt'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='quiz.answeroption'),
        ),
    ]
