# Generated by Django 5.1.3 on 2024-11-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
