# Generated by Django 5.1.1 on 2024-10-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='invited_emails',
            field=models.TextField(blank=True, verbose_name='Invited Candidates'),
        ),
        migrations.CreateModel(
            name='InvitedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_candidates_list', to='assessments.assessment')),
            ],
        ),
    ]
