# Generated by Django 5.0.9 on 2024-11-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_studentassessmentattempt_duration'),
        ('exercises', '0002_programminglanguage_exercise_setup_and_more'),
        ('quiz', '0003_remove_studentanswer_selected_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='exercise_score_ratio',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='quiz_score_ratio',
        ),
        migrations.RemoveField(
            model_name='studentassessmentattempt',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='studentassessmentattempt',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='attempt',
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='user_answers',
            field=models.ManyToManyField(blank=True, related_name='attempts', to='assessments.useranswer'),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='user_submissions',
            field=models.ManyToManyField(blank=True, related_name='attempts', to='exercises.submission'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='assessment',
            field=models.ForeignKey(default=0.0005002501250625312, on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.assessmenttype'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='quiz.question'),
        ),
    ]
