# Generated by Django 5.1.1 on 2024-11-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('assessments', '0003_studentassessmentattempt_duration'),
    ]

    operations = [
    ]
