# Generated by Django 5.0.9 on 2024-11-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_assessment_exercise_score_ratio_and_more'),
        ('exercises', '0002_programminglanguage_exercise_setup_and_more'),
        ('quiz', '0003_remove_studentanswer_selected_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassessmentattempt',
            name='user_answers',
        ),
        migrations.RemoveField(
            model_name='studentassessmentattempt',
            name='user_submissions',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='assessment',
        ),
        migrations.AddField(
            model_name='assessment',
            name='exercise_score_ratio',
            field=models.IntegerField(default=60, verbose_name='Exercise score ratio'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='quiz_score_ratio',
            field=models.IntegerField(default=40, verbose_name='Quiz score ratio'),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(default=0.0005002501250625312, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='assessments.studentassessmentattempt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='assessments.assessmenttype'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='assessment', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assessment', to='quiz.question'),
        ),
    ]
