# Generated by Django 5.0.9 on 2024-10-16 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_total_score'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(default=0.0005002501250625312, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course.course', verbose_name='Course'),
            preserve_default=False,
        ),
    ]
