# Generated by Django 5.0.9 on 2024-10-16 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_quiz', models.IntegerField(default=0, verbose_name='Score')),
                ('score_ass', models.IntegerField(default=0, verbose_name='Score')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Assignment Attempt',
                'verbose_name_plural': 'Student Assignment Attempts',
            },
        ),
    ]
