# Generated by Django 5.0.9 on 2024-10-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_studentassessmentattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='score_ass',
            field=models.IntegerField(default=0, verbose_name='Assignment Score'),
        ),
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='score_quiz',
            field=models.IntegerField(default=0, verbose_name='Quiz Score'),
        ),
    ]
