# Generated by Django 5.1.1 on 2024-11-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_remove_useranswer_selected_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_option',
        ),
    ]
