# Generated by Django 5.0.1 on 2024-11-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_remove_useranswer_selected_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='proctoring_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
