# Generated by Django 5.0.1 on 2024-11-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_studentassessmentattempt_proctoring_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='weights',
            field=models.FloatField(default=1.0, verbose_name='Weights'),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='ass_weights',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='quiz_weights',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
