# Generated by Django 5.0.1 on 2024-11-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_assessmentfinalscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='ass_weights',
            field=models.FloatField(blank=True, default=0.4, null=True),
        ),
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='quiz_weights',
            field=models.FloatField(blank=True, default=0.6, null=True),
        ),
    ]
