# Generated by Django 5.0.1 on 2024-11-12 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_remove_assessmentfinalscore_assessment_and_more'),
        ('course', '0004_alter_enrollment_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassessmentattempt',
            options={'verbose_name': 'Student Assignment Attempt', 'verbose_name_plural': 'Student Assignmenint Attempts'},
        ),
        migrations.RemoveField(
            model_name='assessmentfinalscore',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='assessmentfinalscore',
            name='course',
        ),
        migrations.AddField(
            model_name='assessmentfinalscore',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment', verbose_name='Course'),
        ),
        migrations.CreateModel(
            name='CourseFinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('score', models.FloatField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
