# Generated by Django 5.0.1 on 2024-11-12 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_alter_coursefinalscore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentfinalscore',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment'),
        ),
    ]
