# Generated by Django 5.0.1 on 2024-11-12 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_alter_assessmentfinalscore_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentfinalscore',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment'),
        ),
    ]
