# Generated by Django 5.0.1 on 2024-11-12 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_alter_assessmentfinalscore_assessment'),
        ('course', '0004_alter_enrollment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefinalscore',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
