# Generated by Django 5.0.1 on 2024-11-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_alter_coursefinalscore_course'),
        ('course', '0006_rename_course_weight_course_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course.course'),
        ),
    ]
