# Generated by Django 5.0.1 on 2024-11-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_rename_weights_assessment_assessment_weights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefinalscore',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
