# Generated by Django 5.0.9 on 2024-10-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="course_name",
        ),
    ]
