# Generated by Django 5.0.9 on 2024-11-06 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursematerial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("assignments", "Assignments"),
                    ("labs", "Labs"),
                    ("lectures", "Lectures"),
                    ("references", "References"),
                    ("assessments", "Assessments"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
