# Generated by Django 5.0.9 on 2024-11-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_coursematerial_material_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
