# Generated by Django 5.0.9 on 2024-11-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_course_published_delete_usercourseprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="date_unenrolled",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
