# Generated by Django 5.0.1 on 2024-11-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_weight',
            field=models.FloatField(default=1.0, editable=False),
        ),
    ]
