# Generated by Django 5.0.1 on 2024-11-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_course_weight_course_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='weights',
        ),
    ]
