# Generated by Django 5.0.9 on 2024-11-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_readingmaterial_pdf_file_alter_course_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingmaterial',
            name='pdf_file',
        ),
    ]
