# Generated by Django 5.1.1 on 2024-11-05 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_member_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('manager', 'Manager'), ('member', 'Member')], max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.member')),
            ],
        ),
    ]
