# Generated by Django 5.1.1 on 2024-11-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_teammaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('leader', 'Leader'), ('manager', 'Manager'), ('member', 'Member')], max_length=10),
        ),
        migrations.DeleteModel(
            name='TeamMaterial',
        ),
    ]
