# Generated by Django 5.0.9 on 2024-10-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "permissions": [
                    ("can_view_quiz_results", "Can view quiz results"),
                    ("can_take_quiz", "Can take quiz"),
                ]
            },
        ),
    ]
