# Generated by Django 5.1.1 on 2024-10-28 13:49

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='quiz.answeroption'),
        ),
    ]