# Generated by Django 5.1.1 on 2024-10-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_studentanswer_selected_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_option',
        ),
    ]
