# Generated by Django 5.1.1 on 2024-10-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_receiver_groupchat_chat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
