# Generated by Django 5.1.2 on 2024-11-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('chat', '0004_chat_is_read'),
    ]

    operations = [
    ]
