# Generated by Django 5.0.9 on 2024-10-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("subject", "0004_readingmaterial_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="subject.subject"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("category_name",)},
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("subcategory_name", "parent_category")},
        ),
    ]
