# Generated by Django 5.0.9 on 2024-11-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionthread',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='discussionthread',
            name='loves_count',
        ),
    ]
