# Generated by Django 5.1.2 on 2024-12-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_threadreport_delete_reportthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthread',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='report_threshold',
            field=models.IntegerField(default=30),
        ),
    ]
