# Generated by Django 5.0.9 on 2024-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thread", "0004_threadreport_delete_reportthread"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionthread",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
