# Generated by Django 5.1.2 on 2024-12-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_discussionthread_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthread',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
