# Generated by Django 5.1.2 on 2024-12-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_discussionthread_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionthread',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='discussionthread',
            name='report_threshold',
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='_is_hidden',
            field=models.BooleanField(db_column='is_hidden', default=False),
        ),
    ]
