# Generated by Django 5.0.9 on 2024-09-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.subcategory",
            ),
        ),
    ]
