# Generated by Django 5.0.9 on 2024-10-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="events_files/"),
        ),
        migrations.AddField(
            model_name="news",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="news_files/"),
        ),
    ]
