# Generated by Django 5.1.1 on 2024-10-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'permissions': [('can_delete_user', 'Can delete user'), ('can_add_user', 'Can add user'), ('can_edit_user', 'Can edit user'), ('can_export_users', 'Can export users'), ('can_import_users', 'Can import users'), ('can_detail_user', 'Can detail user'), ('can_delete_department', 'Can delete department'), ('can_add_department', 'Can add department'), ('can_edit_department', 'Can edit department'), ('can_detail_department', 'Can detail department')]},
        ),
    ]
