# Generated by Django 5.0.9 on 2024-11-12 08:52

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('language', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='setup',
            field=models.TextField(blank=True, help_text='Setup code for hard exercises', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.programminglanguage'),
        ),
    ]
