# Generated by Django 5.0.9 on 2024-11-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_programminglanguage_exercise_setup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
