# Generated by Django 5.0.9 on 2024-11-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='setup',
            field=models.TextField(blank=True, help_text='Setup code for hard exercises', null=True),
        ),
    ]
