# Generated by Django 5.0.9 on 2024-11-11 09:25

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_programminglanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.programminglanguage'),
        ),
    ]
