# Generated by Django 5.1.2 on 2024-11-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceanalytics',
            old_name='average_score',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='performanceanalytics',
            name='completion_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performanceanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
