# Generated by Django 5.0.9 on 2024-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="is_prerequisite_for", to="subject.subject"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Prerequisite",
        ),
    ]
