# Generated by Django 5.0.9 on 2024-10-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completion",
            unique_together={("subject", "document", "video", "reading")},
        ),
        migrations.CreateModel(
            name="SubjectMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_id", models.PositiveIntegerField()),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Video"),
                            ("reading", "Reading Material"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="subject.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
