# Generated by Django 5.0.9 on 2024-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0002_subject_prerequisites_subject_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
