# Generated by Django 5.0.9 on 2024-11-18 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_discount_course_price_and_more'),
        ('user', '0003_alter_profile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='students', to='course.course')),
                ('taught_courses', models.ManyToManyField(blank=True, related_name='instructors', to='course.course')),
            ],
        ),
    ]
