# Generated by Django 5.0.9 on 2024-11-21 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bank', '0002_quizbank_quizbank_questio_bdded2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Chapter',
                'indexes': [models.Index(fields=['chapter_name'], name='Chapter_chapter_0f5224_idx')],
            },
        ),
        migrations.AddField(
            model_name='quizbank',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_bank.chapter'),
        ),
    ]
