# Generated by Django 5.1.1 on 2024-09-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='exams/')),
                ('number_of_exams', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_questions', models.IntegerField()),
            ],
        ),
    ]
