# Generated by Django 5.1.2 on 2024-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
