# Generated by Django 5.1.2 on 2024-11-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
