# Generated by Django 5.1.1 on 2024-10-24 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Assignment Attempt',
                'verbose_name_plural': 'Student Assignment Attempts',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=100, verbose_name='Assignment Name')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Assignment Content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coding_exercises', models.ManyToManyField(blank=True, related_name='assignments', to='exercises.exercise', verbose_name='Coding Exercises')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
        ),
    ]
