# Generated by Django 5.0.9 on 2024-10-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_assignment_content_and_more'),
        ('course', '0002_initial'),
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['start_date'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_content',
        ),
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Assignment Content'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=0.0005002501250625312, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course.course', verbose_name='Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(max_length=100, verbose_name='Assignment Name'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='coding_exercises',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='exercises.exercise', verbose_name='Coding Exercises'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
