# Generated by Django 5.0.9 on 2024-10-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_assignment_options_remove_assignment_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignmentattempt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentassignmentattempt',
            name='created_by',
        ),
    ]
