# Generated by Django 5.1.1 on 2024-10-24 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='department', to='course.course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(related_name='department', to=settings.AUTH_USER_MODEL),
        ),
    ]
